name:                midriff
version:             0.1.0
github:              "githubuser/midriff"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "(c) 2020 Author name here"
# category:            Undefined
# synopsis:            Undefined

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/githubuser/midriff#readme>

dependencies:
- base >= 4.12 && < 5

default-extensions:
  - ConstraintKinds
  - DeriveFunctor
  - DeriveFoldable
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - MultiParamTypeClasses
  - Rank2Types
  - TypeApplications
  - TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

executables:
  midriff-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - midriff

tests:
  midriff-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - midriff
    - tasty
    - tasty-hunit
