name:                midriff
version:             0.1.0
github:              "ejconlon/midriff"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2023 Eric Conlon"
# category:            Undefined
# synopsis:            Undefined

language: GHC2021

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/midriff#readme>

dependencies:
- base >= 4.12 && < 5
- async >= 2.2.2 && < 3
- containers >= 0.6.2.1 && < 1
- deepseq >= 1.4.4.0 && < 2
- little-rio >= 2.0.0 && < 3
- primitive >= 0.7 && < 0.9
- resourcet >= 1.2.4.2 && < 2
- RtMidi >= 0.7.0.0 && < 1
- stm >= 2.5.0.0 && < 3
- unliftio-core >= 0.1.2.0 && < 1
- vector >= 0.12.1.2 && < 1
- dahdit
- midiot
- dahdit-network
- optics
- transformers
- mtl
- contravariant
- foldl
- profunctors
- mmorph
- exceptions

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- Rank2Types
- StandaloneDeriving
- TypeApplications
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

executables:
  midriff-exe:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - midriff

tests:
  midriff-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - midriff
    - hedgehog >= 1.0.3 && < 2
    - tasty >= 1.2.3 && < 2
    - tasty-hunit >= 0.10.0.2 && < 1
    - tasty-hedgehog >= 1.0.0.2 && < 2
