name:                midriff
version:             0.1.0
github:              "ejconlon/midriff"
license:             BSD3
author:              "Eric Conlon"
maintainer:          "ejconlon@gmail.com"
copyright:           "(c) 2023 Eric Conlon"
# category:            Undefined
# synopsis:            Undefined

language: GHC2021

extra-source-files:
- README.md

description: Please see the README on GitHub at <https://github.com/ejconlon/midriff#readme>

dependencies:
- base >= 4.12 && < 5
- async >= 2.2.2 && < 3
- containers >= 0.6.2.1 && < 1
- contravariant >= 1.5 && < 1.6
- dahdit >= 0.4.1 && < 0.5
- dahdit-network >= 0.1 && < 0.2
- deepseq >= 1.4.4.0 && < 2
- exceptions >= 0.10 && < 0.11
- foldl >= 1.4 && < 1.5
- little-rio >= 2.0.0 && < 3
- midiot >= 0.1 && < 0.2
- mmorph >= 1.2 && < 1.3
- mtl >= 2.2 && < 2.4
- network >= 3.1 && < 3.2
- optics >= 0.4 && < 0.5
- primitive >= 0.7 && < 0.9
- prettyprinter >= 1.7 && < 1.8
- profunctors >= 5.6 && < 5.7
- resourcet >= 1.2.4.2 && < 2
- RtMidi >= 0.7.0.0 && < 1
- stm >= 2.5.0.0 && < 3
- text >= 1.2 && < 2.1
- transformers >= 0.5 && < 0.7
- unliftio-core >= 0.1.2.0 && < 1
- vector >= 0.12.1.2 && < 1

default-extensions:
- BangPatterns
- ConstraintKinds
- DeriveFunctor
- DeriveFoldable
- DeriveGeneric
- DeriveTraversable
- DerivingStrategies
- DerivingVia
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- Rank2Types
- StandaloneDeriving
- TypeApplications
- TypeFamilies

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-unused-top-binds

library:
  source-dirs: src

executables:
  midriff-exe:
    main:                Main.hs
    source-dirs:         exe
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - midriff

tests:
  midriff-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - midriff
    - hedgehog >= 1.0.3 && < 2
    - tasty >= 1.2.3 && < 2
    - tasty-hunit >= 0.10.0.2 && < 1
    - tasty-hedgehog >= 1.0.0.2 && < 2
