name: haskell-stack
on:
- push
- pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        if [ -f .github/packages.txt ]; then apt-get update && apt-get install -y $(cat .github/packages.txt); fi
    - uses: actions/checkout@v3
    - uses: freckle/stack-action@v4
      with:
        pedantic: false
