name: haskell-stack
on:
- push
- pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo apt update
        sudo apt install -y libasound2-dev libjack-dev
    - uses: actions/checkout@v3
    - uses: freckle/stack-action@v4
      with:
        pedantic: false
